# Build Stage
FROM node:20-slim AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Production Stage
FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV production
ENV PORT 9000

# Copy necessary files
# Next.js standalone output includes everything needed to run the app
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 9000

# Use the server.js generated by standalone output
CMD ["node", "server.js"]
